### ISSUE TITLE
Dokumentation: Berechnung Pixel zu Schritt

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#114]

**Comment by alexsuter** [comment]
def calculateSteps(self, x, width, zuschnitt):
        winkelStepperProSchritt = float(0.0023736)
        c = float(float(width) / 2)
        d = float(99) \* float(1 - float(zuschnitt / 640))
        tmp=float(float(float(float(d)/float(c)) \* float(float(x)-float(c))/190))
        return float(math.atanh(tmp)/float(winkelStepperProSchritt)) \* float(100)

**Comment by adyvs** [comment]
Winkelberechnung file
