### ISSUE TITLE
Source-Code Dokumentation erstellen

### ISSUE THREAD

**Issue by fabwu** [accefa/pren2#117]

**Comment by alexsuter** [comment]
CD macht alex

**Comment by alexsuter** [comment]
- Sicherlich github links
- raspicontroller
- fotoshoot-ui
- freedom board kot

**Comment by alexander-suter** [comment]
- Sicherlich github links

- raspicontroller
- fotoshoot-ui
- freedom board kot

**Comment by alexander-suter** [comment]
- Sicherlich github links

- raspicontroller
- fotoshoot-ui
- freedom board kot

**Comment by alexander-suter** [comment]
- Sicherlich github links

- raspicontroller
- fotoshoot-ui
- freedom board kot
