### ISSUE TITLE
Doku: Projektmanagement

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#127]
Grobplanung: Text hinzufügen, eventuell Hochkant
Fazit an den Schluss vom Projektmanagement - und Fazit Inhalt über das gesamte Projektmanagement. 
Risiko davor nehmen
Projektkosten nicht vergessen

**Comment by Sherekin** [comment]
Erledigt
Review
Projektkosten sind Aufgabe von Adriano (Issue existiert schon länger)
