### ISSUE TITLE
Dokumentation: ET-Schnittstellen dokumentieren

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#39]

**Comment by alexsuter** [comment]
@ninux  hier der task um die schnittstellen zu dokumentieren

**Comment by alexsuter** [comment]
gui - pi - frdm

**Comment by alexander-suter** [comment]
mock

**Comment by fabwu** [comment]
![img_20150326_110147](https://cloud.githubusercontent.com/assets/6050639/6844025/a569b2f4-d3a8-11e4-9c56-90827c471333.jpg)

**Comment by fabwu** [comment]
Status von Motoren im Debug mit einem Aktualisieren-Button abfragen anstatt über Webserver zurückmelden.

**Comment by fabwu** [comment]
RPM und Steps werden während des Ablaufs berechnet. Das GUI für die Motoren sind rein zu debugging Zwecke

**Comment by alexsuter** [comment]
@wuethrich44  Das dokumentiere dann ich

**Comment by alexsuter** [comment]
Wird im #96 erledigt.
