### ISSUE TITLE
DC-Motor Software erstellen

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#47]

**Comment by alexsuter** [comment]
@ninux STATUS??????

**Comment by alexsuter** [comment]
@ninux  ?????? ervin??????

**Comment by Sherekin** [comment]
Ervin sagt gemacht und wir sollen endlich mal die Schnauze halten @wuethrich44 :fu:

**Comment by fabwu** [comment]
@Sherekin :shipit:
