### ISSUE TITLE
Anleitung für GitHub

### ISSUE THREAD

**Issue by ninux** [accefa/pren2#5]
Eine kleine Anleitung schreiben wie GitHub zu nutzen ist. Hierzu gehört insbesondere 
- wie die Planung organisiert ist (Milestone, Issue, etc.)
- wie die Struktur der Organisation/Repositories ist

Kapitel und Abschnitte
- [x] Einleitung
- [x] Issues
- [x] Milestones
- [x] Organisations- und Managementprozess
- [x] Bedienung Webinterface

**Comment by ninux** [comment]
Ich habe eine erste Fassung erstellt. Kannst du dies bitte kurz durchlesen und auf Korrektheit prüfen?

Das Makefile dazu ist vorbereitet (einfach 'make all' ausführen).

**Comment by alexsuter** [comment]
Hoi Ervin ich habe typos korrigiert. Ich muss nicht sagen, dass die Arbeit sehr gut ist, aber ich denke es ist einfach too much. Aber zu viel ist in der Regel besser als zu wenig. jedenfalls Danke!

Schau doch noch mal das File an.
https://github.com/accefa/pren2/blob/master/tex/github/content/process.tex#L41
Auf Zeile 42 beginnt ein Satz, den ich nicht verstehe. Eventuell umformulieren.

**Comment by ninux** [comment]
Vielen Dank für die vielen Sichtungen!

Bezüglich des Umfangs hatte ich auch so meine Zweifel aber ich denke wir können es ja mal so lassen und dann allenfalls kürzen bei der Besprechung im Team am Donnerstag.

Zur Zeile mit dem komischen Satz: Da scheint wirklich was schief gegangen zu sein =) habe mich mal der Sache angenommen.

**Comment by ninux** [comment]
Ich habe noch eine Ergänzung gemacht und den Pre-Release erstellt. Falls keine witeren Inputs/Änderungswünsche kommen, dann mache ich den Release daraus. Dannk können wir diese Dokumentation abgeben.

**Comment by ninux** [comment]
Per Mail an Dozenten gesendet.
