### ISSUE TITLE
Raspberry Pi: Libs installieren

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#59]
Um Texte aufs Bild zu schreiben:
ImportError: The _imagingft C module is not installed               

Um mit JPEG Images zu arbeiten:
IOError: decoder jpeg not available

**Comment by alexsuter** [comment]
:fu: :fu: :fu: 
JPEG können nun verarbeitet werden. 1. Deinstallieren von Pillow     2. Installieren von libjpeg    3. Installieren von Pillow
Grund: Pillow muss damit kompiliert werden

Nun zum nächsten....

**Comment by alexsuter** [comment]
Dasselbe hier: :fu: :fu: :fu: 
pacman -S freetype2

Pillow deinstallieren und wieder installieren. Ich drehe durch.

**Comment by alexsuter** [comment]
Done. Yeah. :grapes:

**Comment by fabwu** [comment]
Python hald :fu:
