### ISSUE TITLE
Komponentendiagramm erstellen

### ISSUE THREAD

**Issue by fabwu** [accefa/pren2#6]

**Comment by fabwu** [comment]
@alexander-suter Kannst du mal reviewen?

**Comment by alexsuter** [comment]
hey ciao. ich has agluegt. ich finds guet.

gids eventuell no en witeri komponente? die wo defür verantwortlich isch um kamera istellige vorzneh, oder machemer das implizit mit de Detection Komponente? 

Wenn ichs mier ez no eisch überlege, chamer ja das mit de Detection Komponete mache. Will das sind ja nur Istellige vo de Detection Komponente wo die Komponente entgegenimmt und ufgrund vo dene istellige nacher Detection macht.

Also ich denke mit Text nacher i de Doku. Isch das ok!

**Comment by fabwu** [comment]
:+1:
