### ISSUE TITLE
Ablauf der Einrichtung (5min) definieren

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#69]
Ablaufplan erstellen und definieren, welche Parameter eingestellt werden, falls unerwartets auftritt.

**Comment by alexsuter** [comment]
Flussidiagramm in Viso erstellen

**Comment by fabwu** [comment]
![img_20150326_110543](https://cloud.githubusercontent.com/assets/6050639/6844032/b67a1f5c-d3a8-11e4-9517-60b0ebe0fa45.jpg)

**Comment by Sherekin** [comment]
PDF erstelt und in Latex eingebunden
