### ISSUE TITLE
Entwicklungsumgebung für Java und Python definieren

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#7]
- Entwickeln
- Deployen
- Debuggen

**Comment by alexsuter** [comment]
Eclipse + PyDev + Pyhton 2.7.x

**Comment by alexsuter** [comment]
In Eclipse kann man direkt debuggen.

**Comment by alexsuter** [comment]
Remote Debugging: 
http://pydev.org/manual_adv_remote_debugger.html

Grösserer Aufwand...

**Comment by alexsuter** [comment]
Unit Test Framework: https://docs.python.org/2/library/unittest.html
Pyhton API: http://www.tutorialspoint.com/python/index.htm

**Comment by alexsuter** [comment]
Von meiner Seite aus Ready: Ich brauche nichts mehr. Ausser eventuell noch ein Deployment Tool?

**Comment by fabwu** [comment]
Für mich passt auch alles. Deployment siehe #8
