### ISSUE TITLE
Projekt Setup für Java und Python Projekte

### ISSUE THREAD

**Issue by alexsuter** [accefa/pren2#8]
- [x] Git Repo
- [x] Python Module?
- [x] Java Maven/Ant?
- [x] Java FX
- [x] Raspberri PI Runtime
- [x] Deployment auf Raspberry PI

**Comment by alexsuter** [comment]
Bist du zufrieden mit den bisherigen ersten 4 Punkten?
Wie deployen wir nun?

**Comment by fabwu** [comment]
Die einzige Bibliothek die wir nicht auf dem Laptop gebrauchen können ist ja picamera. Wenn wir aber einen Mock erstellen der uns immer ein Bild zurückliefert können wir auf dem Laptop entwickeln und mit WinSCP deployen. Ich denke das wäre die sinnvollste Lösung.

**Comment by alexsuter** [comment]
Tip top. Das deployen umfasst ja nur das kopieren von Dateien.
Ich close somite diesen Issue.
