### ISSUE TITLE
Dokumentation: schnittstellen

### ISSUE THREAD

**Issue by Sherekin** [accefa/pren2#96]

**Comment by alexsuter** [comment]
Ich dokumentiere die IT-Schnittstellen:
- Überarbeiten der REST-Schnittstellen
- Dokumentation der IT-ET Schnittstellen
- Frage an @ninux : Hast Du auch Schnittstellen die dokumentiert werden müssen? Bswp: FreedoamBoard - zu Motoren Treiber?

**Comment by alexsuter** [comment]
Informationen dazu im #39
